name: Standard Notes Client

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-18.04
         
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Build and test with Rake
        run: |
          gem install bundler && bundle install

  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t standardnotes .
      - name: Tags
        run: |
          docker tag standardnotes ${{ secrets.DOCKER_USER }}/standardnotes:${{ github.sha }}
          docker tag standardnotes ${{ secrets.DOCKER_USER }}/standardnotes:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/standardnotes:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/standardnotes:latest
